# Generated by Django 5.1.4 on 2024-12-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address_profile_city_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='users_profile',
        ),
    ]
